[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "ytcli"
version = "0.1.0"
description = "TUI e daemon para tocar músicas do YouTube Music com MPV"
authors = [{name = "Seu Nome"}]
dependencies = [
    "rich==13.7.0",
    "requests==2.31.0",
    "fastapi==0.109.0",
    "uvicorn==0.23.2",
    "yt-dlp",
    "python-mpv==1.0.8",
    "textual>=0.60.0"
    
]

[project.scripts]
music_tui = "music_tui:main"
musicd = "musicd:main"


[tool.setuptools]
py-modules = ["music_tui", "musicd"]

[tool.setuptools.package-data]
ytcli = ["bin/*"]